CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(30) NOT NULL,
  password VARCHAR(30) NOT NULL,
);

CREATE TABLE appointments AS SELECT id FROM users; (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  appointments VARCHAR(30) NOT NULL,
  date VARCHAR(10) NOT NULL
);